version: '3.8'

# Enable BuildKit for cache mounts
x-build-config: &build-config
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

services:
  webexdx-mongodb:
    image: mongo:latest
    container_name: webexdx-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - webexdx-mongo-data:/data/db
  kafka:
    image: apache/kafka:4.1.2
    container_name: kafka
    ports:
      - "9092:29092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  webexdx-email-service:
    build:
      context: ../webexdx-email-service
      dockerfile: Dockerfile
    container_name: email-service
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092

  webexdx-auth-service:
    build:
      context: ../webexdx-auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9092
    ports:
      - "3000:3000"

  webexdx-taskify-service:
    build:
      context: ../webexdx-taskify-service
      dockerfile: Dockerfile
    container_name: taskify-service
    ports:
      - "3002:3002"
  webexdx-configforge-service:
    build:
      context: ../webexdx-configforge-service
      dockerfile: Dockerfile
    container_name: configforge-service
    ports:
      - "3001:3001"
  webexdx-auth-mfe:
    build:
      context: ../webexdx-auth-mfe
      dockerfile: Dockerfile
    container_name: auth-mfe
    ports:
      - "4000:80"
  webexdx-taskify-mfe:
    build:
      context: ../webexdx-taskify-mfe
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: dev
    container_name: taskify-mfe
    ports:
      - "4001:80"
  webexdx-configforge-mfe:
    build:
      context: ../webexdx-configforge-mfe
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: dev
    container_name: configforge-mfe
    ports:
      - "4002:80"

volumes:
  webexdx-mongo-data:
  kafka_data:
